export { default as AddBtnIcon } from "@/assets/icons/add_btn.svg"
export { default as PhotoChangeIcon } from "@/assets/icons/profile.svg"
export { default as ProfileIcon } from "@/assets/icons/profile.svg"
export { default as CloseIcon } from "@/assets/icons/close.svg"
export { default as ArrowIcon } from "@/assets/icons/arrow-black.svg"
export { default as GoOutIcon } from "@/assets/icons/goout.svg"
export { default as SearchIcon } from "@/assets/icons/search.svg"
export { default as DeleteIcon } from "@/assets/icons/btn_delete.svg"
